# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Log_in(object):
    def setupUi(self, Log_in):
        Log_in.setObjectName("Log_in")
        Log_in.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Log_in.sizePolicy().hasHeightForWidth())
        Log_in.setSizePolicy(sizePolicy)
        self.formLayout_3 = QtWidgets.QFormLayout(Log_in)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Anuncio = QtWidgets.QLabel(Log_in)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Anuncio.setFont(font)
        self.Anuncio.setObjectName("Anuncio")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Anuncio)
        self.line = QtWidgets.QFrame(Log_in)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.Lb_Usuario = QtWidgets.QLabel(Log_in)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Lb_Usuario.setFont(font)
        self.Lb_Usuario.setAutoFillBackground(False)
        self.Lb_Usuario.setObjectName("Lb_Usuario")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Lb_Usuario)
        self.text_usuario = QtWidgets.QLineEdit(Log_in)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.text_usuario.setFont(font)
        self.text_usuario.setObjectName("text_usuario")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.text_usuario)
        self.Lb_constrasena = QtWidgets.QLabel(Log_in)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Lb_constrasena.setFont(font)
        self.Lb_constrasena.setObjectName("Lb_constrasena")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Lb_constrasena)
        self.text_contrasena = QtWidgets.QLineEdit(Log_in)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.text_contrasena.setFont(font)
        self.text_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_contrasena.setObjectName("text_contrasena")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_contrasena)
        self.BtnEntrar = QtWidgets.QPushButton(Log_in)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.BtnEntrar.setFont(font)
        self.BtnEntrar.setObjectName("BtnEntrar")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.BtnEntrar)
        self.lbReloj = QtWidgets.QLabel(Log_in)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(14)
        self.lbReloj.setFont(font)
        self.lbReloj.setObjectName("lbReloj")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbReloj)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout_2)

        self.retranslateUi(Log_in)
        QtCore.QMetaObject.connectSlotsByName(Log_in)

    def retranslateUi(self, Log_in):
        _translate = QtCore.QCoreApplication.translate
        Log_in.setWindowTitle(_translate("Log_in", "Dialog"))
        self.Anuncio.setText(_translate("Log_in", "Abarrotes \"tienda\""))
        self.Lb_Usuario.setText(_translate("Log_in", "Usuario:"))
        self.Lb_constrasena.setText(_translate("Log_in", "Contraseña:"))
        self.BtnEntrar.setText(_translate("Log_in", "Entrar"))
        self.lbReloj.setText(_translate("Log_in", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Log_in = QtWidgets.QDialog()
    ui = Ui_Log_in()
    ui.setupUi(Log_in)
    Log_in.show()
    sys.exit(app.exec_())
